// Code generated by "stringer -type=LoginState"; DO NOT EDIT.

package scdhandler

import "fmt"

const _LoginState_name = "LoginNoneLoginU2FLoginChangePasswordLoginGranted"

var _LoginState_index = [...]uint8{0, 9, 17, 36, 48}

func (i LoginState) String() string {
	if i < 0 || i >= LoginState(len(_LoginState_index)-1) {
		return fmt.Sprintf("LoginState(%d)", i)
	}
	return _LoginState_name[_LoginState_index[i]:_LoginState_index[i+1]]
}
