// Code generated by "stringer -type=LoginState"; DO NOT EDIT.

package handler

import "fmt"

const _LoginState_name = "LoginErrorLoginNoneLoginU2FLoginChangePasswordLoginGranted"

var _LoginState_index = [...]uint8{0, 10, 19, 27, 46, 58}

func (i LoginState) String() string {
	i -= -1
	if i < 0 || i >= LoginState(len(_LoginState_index)-1) {
		return fmt.Sprintf("LoginState(%d)", i+-1)
	}
	return _LoginState_name[_LoginState_index[i]:_LoginState_index[i+1]]
}
