// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type HTTPRequest struct {
	Host string `protobuf:"bytes,1,opt,name=Host" json:"Host,omitempty"`
	// Method specifies the HTTP method (GET, POST, PUT, etc.).
	Method string `protobuf:"bytes,2,opt,name=Method" json:"Method,omitempty"`
	// URL specifies either the URI being requested.
	URL *URL `protobuf:"bytes,3,opt,name=URL" json:"URL,omitempty"`
	// The protocol version for incoming server requests.
	ProtoMajor  int32         `protobuf:"varint,4,opt,name=ProtoMajor" json:"ProtoMajor,omitempty"`
	ProtoMinor  int32         `protobuf:"varint,5,opt,name=ProtoMinor" json:"ProtoMinor,omitempty"`
	Header      *KeyValueList `protobuf:"bytes,6,opt,name=Header" json:"Header,omitempty"`
	Body        []byte        `protobuf:"bytes,7,opt,name=Body,proto3" json:"Body,omitempty"`
	ContentType string        `protobuf:"bytes,8,opt,name=ContentType" json:"ContentType,omitempty"`
	// RemoteAddr allows HTTP servers and other software to record
	// the network address that sent the request, usually for
	// logging. This field is not filled in by ReadRequest and
	// has no defined format. The HTTP server in this package
	// sets RemoteAddr to an "IP:port" address before invoking a
	// handler.
	RemoteAddr string           `protobuf:"bytes,9,opt,name=RemoteAddr" json:"RemoteAddr,omitempty"`
	TLS        *TLSState        `protobuf:"bytes,10,opt,name=TLS" json:"TLS,omitempty"`
	Auth       *RequestAuthResp `protobuf:"bytes,11,opt,name=Auth" json:"Auth,omitempty"`
	Config     *ConfigureURL    `protobuf:"bytes,12,opt,name=Config" json:"Config,omitempty"`
	Version    string           `protobuf:"bytes,13,opt,name=Version" json:"Version,omitempty"`
}

func (m *HTTPRequest) Reset()                    { *m = HTTPRequest{} }
func (m *HTTPRequest) String() string            { return proto.CompactTextString(m) }
func (*HTTPRequest) ProtoMessage()               {}
func (*HTTPRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *HTTPRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *HTTPRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *HTTPRequest) GetURL() *URL {
	if m != nil {
		return m.URL
	}
	return nil
}

func (m *HTTPRequest) GetProtoMajor() int32 {
	if m != nil {
		return m.ProtoMajor
	}
	return 0
}

func (m *HTTPRequest) GetProtoMinor() int32 {
	if m != nil {
		return m.ProtoMinor
	}
	return 0
}

func (m *HTTPRequest) GetHeader() *KeyValueList {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *HTTPRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *HTTPRequest) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *HTTPRequest) GetRemoteAddr() string {
	if m != nil {
		return m.RemoteAddr
	}
	return ""
}

func (m *HTTPRequest) GetTLS() *TLSState {
	if m != nil {
		return m.TLS
	}
	return nil
}

func (m *HTTPRequest) GetAuth() *RequestAuthResp {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *HTTPRequest) GetConfig() *ConfigureURL {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *HTTPRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type HTTPResponse struct {
	Header *KeyValueList `protobuf:"bytes,1,opt,name=Header" json:"Header,omitempty"`
	// Content type of the body.
	ContentType string `protobuf:"bytes,2,opt,name=ContentType" json:"ContentType,omitempty"`
	// Encoding of the response. Often a compression method like "gzip" or "br".
	Encoding string `protobuf:"bytes,3,opt,name=Encoding" json:"Encoding,omitempty"`
	Body     []byte `protobuf:"bytes,4,opt,name=Body,proto3" json:"Body,omitempty"`
}

func (m *HTTPResponse) Reset()                    { *m = HTTPResponse{} }
func (m *HTTPResponse) String() string            { return proto.CompactTextString(m) }
func (*HTTPResponse) ProtoMessage()               {}
func (*HTTPResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *HTTPResponse) GetHeader() *KeyValueList {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *HTTPResponse) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *HTTPResponse) GetEncoding() string {
	if m != nil {
		return m.Encoding
	}
	return ""
}

func (m *HTTPResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type URL struct {
	Host  string        `protobuf:"bytes,1,opt,name=Host" json:"Host,omitempty"`
	Path  string        `protobuf:"bytes,2,opt,name=Path" json:"Path,omitempty"`
	Query *KeyValueList `protobuf:"bytes,3,opt,name=Query" json:"Query,omitempty"`
}

func (m *URL) Reset()                    { *m = URL{} }
func (m *URL) String() string            { return proto.CompactTextString(m) }
func (*URL) ProtoMessage()               {}
func (*URL) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *URL) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *URL) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *URL) GetQuery() *KeyValueList {
	if m != nil {
		return m.Query
	}
	return nil
}

type StringList struct {
	Value []string `protobuf:"bytes,1,rep,name=Value" json:"Value,omitempty"`
}

func (m *StringList) Reset()                    { *m = StringList{} }
func (m *StringList) String() string            { return proto.CompactTextString(m) }
func (*StringList) ProtoMessage()               {}
func (*StringList) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *StringList) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type KeyValueList struct {
	Values map[string]*StringList `protobuf:"bytes,1,rep,name=Values" json:"Values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *KeyValueList) Reset()                    { *m = KeyValueList{} }
func (m *KeyValueList) String() string            { return proto.CompactTextString(m) }
func (*KeyValueList) ProtoMessage()               {}
func (*KeyValueList) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *KeyValueList) GetValues() map[string]*StringList {
	if m != nil {
		return m.Values
	}
	return nil
}

type TLSState struct {
	Version           uint32 `protobuf:"varint,1,opt,name=Version" json:"Version,omitempty"`
	HandshakeComplete bool   `protobuf:"varint,2,opt,name=HandshakeComplete" json:"HandshakeComplete,omitempty"`
	DidResume         bool   `protobuf:"varint,3,opt,name=DidResume" json:"DidResume,omitempty"`
	CipherSuite       uint32 `protobuf:"varint,4,opt,name=CipherSuite" json:"CipherSuite,omitempty"`
	ServerName        string `protobuf:"bytes,5,opt,name=ServerName" json:"ServerName,omitempty"`
}

func (m *TLSState) Reset()                    { *m = TLSState{} }
func (m *TLSState) String() string            { return proto.CompactTextString(m) }
func (*TLSState) ProtoMessage()               {}
func (*TLSState) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *TLSState) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *TLSState) GetHandshakeComplete() bool {
	if m != nil {
		return m.HandshakeComplete
	}
	return false
}

func (m *TLSState) GetDidResume() bool {
	if m != nil {
		return m.DidResume
	}
	return false
}

func (m *TLSState) GetCipherSuite() uint32 {
	if m != nil {
		return m.CipherSuite
	}
	return 0
}

func (m *TLSState) GetServerName() string {
	if m != nil {
		return m.ServerName
	}
	return ""
}

func init() {
	proto.RegisterType((*HTTPRequest)(nil), "api.HTTPRequest")
	proto.RegisterType((*HTTPResponse)(nil), "api.HTTPResponse")
	proto.RegisterType((*URL)(nil), "api.URL")
	proto.RegisterType((*StringList)(nil), "api.StringList")
	proto.RegisterType((*KeyValueList)(nil), "api.KeyValueList")
	proto.RegisterType((*TLSState)(nil), "api.TLSState")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for HTTP service

type HTTPClient interface {
	ServeHTTP(ctx context.Context, in *HTTPRequest, opts ...grpc.CallOption) (*HTTPResponse, error)
}

type hTTPClient struct {
	cc *grpc.ClientConn
}

func NewHTTPClient(cc *grpc.ClientConn) HTTPClient {
	return &hTTPClient{cc}
}

func (c *hTTPClient) ServeHTTP(ctx context.Context, in *HTTPRequest, opts ...grpc.CallOption) (*HTTPResponse, error) {
	out := new(HTTPResponse)
	err := grpc.Invoke(ctx, "/api.HTTP/ServeHTTP", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HTTP service

type HTTPServer interface {
	ServeHTTP(context.Context, *HTTPRequest) (*HTTPResponse, error)
}

func RegisterHTTPServer(s *grpc.Server, srv HTTPServer) {
	s.RegisterService(&_HTTP_serviceDesc, srv)
}

func _HTTP_ServeHTTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HTTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HTTPServer).ServeHTTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.HTTP/ServeHTTP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HTTPServer).ServeHTTP(ctx, req.(*HTTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HTTP_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.HTTP",
	HandlerType: (*HTTPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServeHTTP",
			Handler:    _HTTP_ServeHTTP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "request.proto",
}

func init() { proto.RegisterFile("request.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 580 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x6d, 0x6b, 0xd4, 0x40,
	0x10, 0x26, 0x97, 0xbb, 0xeb, 0x65, 0x72, 0x87, 0xed, 0x52, 0x64, 0x09, 0xbe, 0x84, 0x80, 0x18,
	0x41, 0x0e, 0xa9, 0x08, 0xc5, 0x6f, 0xb5, 0x16, 0x0e, 0xbd, 0x4a, 0xdd, 0x5c, 0xfb, 0x3d, 0x9a,
	0xb1, 0x89, 0xed, 0x65, 0xe3, 0x66, 0x53, 0xc8, 0x6f, 0xf0, 0x93, 0x7f, 0xc2, 0x1f, 0xe0, 0x2f,
	0x94, 0x9d, 0xa4, 0xbd, 0xc5, 0x2b, 0xf8, 0x6d, 0xe6, 0x99, 0x27, 0xf3, 0xf2, 0xcc, 0x64, 0x61,
	0xa6, 0xf0, 0x47, 0x83, 0xb5, 0x9e, 0x57, 0x4a, 0x6a, 0xc9, 0xdc, 0xb4, 0x2a, 0x02, 0x48, 0x1b,
	0x9d, 0x77, 0x40, 0x30, 0x55, 0xb2, 0xd1, 0xa8, 0x3a, 0x2f, 0xfa, 0xed, 0x82, 0xbf, 0x58, 0xad,
	0xce, 0x44, 0xf7, 0x11, 0x63, 0x30, 0x5c, 0xc8, 0x5a, 0x73, 0x27, 0x74, 0x62, 0x4f, 0x90, 0xcd,
	0x1e, 0xc2, 0xf8, 0x14, 0x75, 0x2e, 0x33, 0x3e, 0x20, 0xb4, 0xf7, 0x58, 0x00, 0xee, 0xb9, 0x58,
	0x72, 0x37, 0x74, 0x62, 0xff, 0x60, 0x32, 0x4f, 0xab, 0x62, 0x7e, 0x2e, 0x96, 0xc2, 0x80, 0xec,
	0x09, 0xc0, 0x99, 0x29, 0x70, 0x9a, 0x7e, 0x97, 0x8a, 0x0f, 0x43, 0x27, 0x1e, 0x09, 0x0b, 0xd9,
	0xc4, 0x8b, 0x52, 0x2a, 0x3e, 0xb2, 0xe3, 0x06, 0x61, 0x2f, 0x60, 0xbc, 0xc0, 0x34, 0x43, 0xc5,
	0xc7, 0x94, 0x7e, 0x8f, 0xd2, 0x7f, 0xc4, 0xf6, 0x22, 0xbd, 0x6e, 0x70, 0x59, 0xd4, 0x5a, 0xf4,
	0x04, 0xd3, 0xf2, 0x3b, 0x99, 0xb5, 0x7c, 0x27, 0x74, 0xe2, 0xa9, 0x20, 0x9b, 0x85, 0xe0, 0x1f,
	0xcb, 0x52, 0x63, 0xa9, 0x57, 0x6d, 0x85, 0x7c, 0x42, 0x7d, 0xdb, 0x90, 0x69, 0x40, 0xe0, 0x5a,
	0x6a, 0x3c, 0xca, 0x32, 0xc5, 0x3d, 0x22, 0x58, 0x08, 0x7b, 0x0a, 0xee, 0x6a, 0x99, 0x70, 0xa0,
	0xea, 0x33, 0xaa, 0xbe, 0x5a, 0x26, 0x89, 0x4e, 0x35, 0x0a, 0x13, 0x61, 0x31, 0x0c, 0x8f, 0x1a,
	0x9d, 0x73, 0x9f, 0x18, 0xfb, 0xc4, 0xe8, 0x55, 0x34, 0xb8, 0xc0, 0xba, 0x12, 0xc4, 0x30, 0xb3,
	0x1c, 0xcb, 0xf2, 0x5b, 0x71, 0xc9, 0xa7, 0xd6, 0x2c, 0x1d, 0xd4, 0x28, 0x34, 0x9a, 0xf5, 0x04,
	0xc6, 0x61, 0xe7, 0x02, 0x55, 0x5d, 0xc8, 0x92, 0xcf, 0xa8, 0xa5, 0x5b, 0x37, 0xfa, 0xe9, 0xc0,
	0xb4, 0x5b, 0x54, 0x5d, 0xc9, 0xb2, 0x46, 0x4b, 0x21, 0xe7, 0x7f, 0x0a, 0xfd, 0xa3, 0xc6, 0x60,
	0x5b, 0x8d, 0x00, 0x26, 0x27, 0xe5, 0x57, 0x99, 0x15, 0xe5, 0x25, 0xed, 0xd3, 0x13, 0x77, 0xfe,
	0x9d, 0xbe, 0xc3, 0x8d, 0xbe, 0xd1, 0x05, 0xad, 0xfe, 0xde, 0x6b, 0x61, 0x30, 0x3c, 0x4b, 0x75,
	0xde, 0x57, 0x21, 0x9b, 0x3d, 0x87, 0xd1, 0xe7, 0x06, 0x55, 0xdb, 0xdf, 0xca, 0x3d, 0xad, 0x76,
	0xf1, 0x28, 0x02, 0x48, 0xb4, 0x2a, 0xca, 0x4b, 0x03, 0xb2, 0x7d, 0x18, 0x11, 0x83, 0x3b, 0xa1,
	0x1b, 0x7b, 0xa2, 0x73, 0xa2, 0x5f, 0x0e, 0x4c, 0xed, 0x6f, 0xd9, 0x1b, 0x18, 0x93, 0x53, 0x13,
	0xcf, 0x3f, 0x78, 0xbc, 0x95, 0x7e, 0xde, 0xc5, 0x4f, 0x4a, 0xad, 0x5a, 0xd1, 0x93, 0x83, 0x0f,
	0xe0, 0x5b, 0x30, 0xdb, 0x05, 0xf7, 0x0a, 0xdb, 0x7e, 0x14, 0x63, 0xb2, 0x67, 0x30, 0xba, 0xa1,
	0xf2, 0x03, 0xea, 0xfa, 0x01, 0xa5, 0xdd, 0xb4, 0x27, 0xba, 0xe8, 0xdb, 0xc1, 0xa1, 0x13, 0xfd,
	0x71, 0x60, 0x72, 0x7b, 0x1e, 0xf6, 0x12, 0x4d, 0xb6, 0xd9, 0xdd, 0x12, 0xd9, 0x4b, 0xd8, 0x5b,
	0xa4, 0x65, 0x56, 0xe7, 0xe9, 0x15, 0x1e, 0xcb, 0x75, 0x75, 0x8d, 0xba, 0xcb, 0x3e, 0x11, 0xdb,
	0x01, 0xf6, 0x08, 0xbc, 0xf7, 0x45, 0x26, 0xb0, 0x6e, 0xd6, 0x48, 0xca, 0x4d, 0xc4, 0x06, 0xa0,
	0xa5, 0x16, 0x55, 0x8e, 0x2a, 0x69, 0x0a, 0x8d, 0xb4, 0x9d, 0x99, 0xb0, 0x21, 0x73, 0xe2, 0x09,
	0xaa, 0x1b, 0x54, 0x9f, 0xd2, 0x35, 0xd2, 0x3f, 0xe6, 0x09, 0x0b, 0x39, 0x38, 0x84, 0xa1, 0xb9,
	0x28, 0xf6, 0x0a, 0x3c, 0x42, 0xc9, 0xd9, 0xa5, 0x29, 0xad, 0x27, 0x21, 0xd8, 0xb3, 0x90, 0xee,
	0xf6, 0xbe, 0x8c, 0xe9, 0xf1, 0x78, 0xfd, 0x37, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x20, 0xc3, 0xce,
	0x6c, 0x04, 0x00, 0x00,
}
