// Code generated by protoc-gen-go. DO NOT EDIT.
// source: router.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type UpdateAction int32

const (
	UpdateAction_UpdateNOOP   UpdateAction = 0
	UpdateAction_UpdateInsert UpdateAction = 1
	UpdateAction_UpdateAlter  UpdateAction = 2
	UpdateAction_UpdateDelete UpdateAction = 3
)

var UpdateAction_name = map[int32]string{
	0: "UpdateNOOP",
	1: "UpdateInsert",
	2: "UpdateAlter",
	3: "UpdateDelete",
}
var UpdateAction_value = map[string]int32{
	"UpdateNOOP":   0,
	"UpdateInsert": 1,
	"UpdateAlter":  2,
	"UpdateDelete": 3,
}

func (x UpdateAction) String() string {
	return proto.EnumName(UpdateAction_name, int32(x))
}
func (UpdateAction) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type ServiceConfigAction int32

const (
	ServiceConfigAction_Add    ServiceConfigAction = 0
	ServiceConfigAction_Remove ServiceConfigAction = 1
)

var ServiceConfigAction_name = map[int32]string{
	0: "Add",
	1: "Remove",
}
var ServiceConfigAction_value = map[string]int32{
	"Add":    0,
	"Remove": 1,
}

func (x ServiceConfigAction) String() string {
	return proto.EnumName(ServiceConfigAction_name, int32(x))
}
func (ServiceConfigAction) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

type ResourceType int32

const (
	ResourceType_ResourceNone    ResourceType = 0
	ResourceType_ResourceURL     ResourceType = 1
	ResourceType_ResourceSPACode ResourceType = 2
	ResourceType_ResourceAuth    ResourceType = 4
	ResourceType_ResourceQuery   ResourceType = 5
)

var ResourceType_name = map[int32]string{
	0: "ResourceNone",
	1: "ResourceURL",
	2: "ResourceSPACode",
	4: "ResourceAuth",
	5: "ResourceQuery",
}
var ResourceType_value = map[string]int32{
	"ResourceNone":    0,
	"ResourceURL":     1,
	"ResourceSPACode": 2,
	"ResourceAuth":    4,
	"ResourceQuery":   5,
}

func (x ResourceType) String() string {
	return proto.EnumName(ResourceType_name, int32(x))
}
func (ResourceType) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

type NotifyReq struct {
	ServiceAddress string `protobuf:"bytes,1,opt,name=ServiceAddress" json:"ServiceAddress,omitempty"`
}

func (m *NotifyReq) Reset()                    { *m = NotifyReq{} }
func (m *NotifyReq) String() string            { return proto.CompactTextString(m) }
func (*NotifyReq) ProtoMessage()               {}
func (*NotifyReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *NotifyReq) GetServiceAddress() string {
	if m != nil {
		return m.ServiceAddress
	}
	return ""
}

type UpdateReq struct {
	Action UpdateAction `protobuf:"varint,1,opt,name=Action,enum=api.UpdateAction" json:"Action,omitempty"`
	Bind   string       `protobuf:"bytes,2,opt,name=Bind" json:"Bind,omitempty"`
	Host   []string     `protobuf:"bytes,3,rep,name=Host" json:"Host,omitempty"`
	Bundle []string     `protobuf:"bytes,4,rep,name=Bundle" json:"Bundle,omitempty"`
}

func (m *UpdateReq) Reset()                    { *m = UpdateReq{} }
func (m *UpdateReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateReq) ProtoMessage()               {}
func (*UpdateReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *UpdateReq) GetAction() UpdateAction {
	if m != nil {
		return m.Action
	}
	return UpdateAction_UpdateNOOP
}

func (m *UpdateReq) GetBind() string {
	if m != nil {
		return m.Bind
	}
	return ""
}

func (m *UpdateReq) GetHost() []string {
	if m != nil {
		return m.Host
	}
	return nil
}

func (m *UpdateReq) GetBundle() []string {
	if m != nil {
		return m.Bundle
	}
	return nil
}

type UpdateResp struct {
}

func (m *UpdateResp) Reset()                    { *m = UpdateResp{} }
func (m *UpdateResp) String() string            { return proto.CompactTextString(m) }
func (*UpdateResp) ProtoMessage()               {}
func (*UpdateResp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

type ServiceConfigEndpoint struct {
	Name     string      `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Endpoint string      `protobuf:"bytes,2,opt,name=Endpoint" json:"Endpoint,omitempty"`
	Resource []*Resource `protobuf:"bytes,3,rep,name=Resource" json:"Resource,omitempty"`
}

func (m *ServiceConfigEndpoint) Reset()                    { *m = ServiceConfigEndpoint{} }
func (m *ServiceConfigEndpoint) String() string            { return proto.CompactTextString(m) }
func (*ServiceConfigEndpoint) ProtoMessage()               {}
func (*ServiceConfigEndpoint) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *ServiceConfigEndpoint) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceConfigEndpoint) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *ServiceConfigEndpoint) GetResource() []*Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

type ServiceConfig struct {
	Version string                   `protobuf:"bytes,1,opt,name=Version" json:"Version,omitempty"`
	Action  ServiceConfigAction      `protobuf:"varint,2,opt,name=Action,enum=api.ServiceConfigAction" json:"Action,omitempty"`
	List    []*ServiceConfigEndpoint `protobuf:"bytes,3,rep,name=List" json:"List,omitempty"`
}

func (m *ServiceConfig) Reset()                    { *m = ServiceConfig{} }
func (m *ServiceConfig) String() string            { return proto.CompactTextString(m) }
func (*ServiceConfig) ProtoMessage()               {}
func (*ServiceConfig) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *ServiceConfig) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ServiceConfig) GetAction() ServiceConfigAction {
	if m != nil {
		return m.Action
	}
	return ServiceConfigAction_Add
}

func (m *ServiceConfig) GetList() []*ServiceConfigEndpoint {
	if m != nil {
		return m.List
	}
	return nil
}

type Resource struct {
	Name          string       `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Parent        string       `protobuf:"bytes,2,opt,name=Parent" json:"Parent,omitempty"`
	Type          ResourceType `protobuf:"varint,3,opt,name=Type,enum=api.ResourceType" json:"Type,omitempty"`
	Consume       ResourceType `protobuf:"varint,4,opt,name=Consume,enum=api.ResourceType" json:"Consume,omitempty"`
	Configuration []byte       `protobuf:"bytes,5,opt,name=Configuration,proto3" json:"Configuration,omitempty"`
	// Include list of other resources this bundle should include.
	Include []string `protobuf:"bytes,6,rep,name=Include" json:"Include,omitempty"`
}

func (m *Resource) Reset()                    { *m = Resource{} }
func (m *Resource) String() string            { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()               {}
func (*Resource) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *Resource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Resource) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Resource) GetType() ResourceType {
	if m != nil {
		return m.Type
	}
	return ResourceType_ResourceNone
}

func (m *Resource) GetConsume() ResourceType {
	if m != nil {
		return m.Consume
	}
	return ResourceType_ResourceNone
}

func (m *Resource) GetConfiguration() []byte {
	if m != nil {
		return m.Configuration
	}
	return nil
}

func (m *Resource) GetInclude() []string {
	if m != nil {
		return m.Include
	}
	return nil
}

type LoginBundle struct {
	LoginState      LoginState `protobuf:"varint,1,opt,name=LoginState,enum=api.LoginState" json:"LoginState,omitempty"`
	Prefix          string     `protobuf:"bytes,2,opt,name=Prefix" json:"Prefix,omitempty"`
	ConsumeRedirect bool       `protobuf:"varint,3,opt,name=ConsumeRedirect" json:"ConsumeRedirect,omitempty"`
	Resource        string     `protobuf:"bytes,4,opt,name=Resource" json:"Resource,omitempty"`
}

func (m *LoginBundle) Reset()                    { *m = LoginBundle{} }
func (m *LoginBundle) String() string            { return proto.CompactTextString(m) }
func (*LoginBundle) ProtoMessage()               {}
func (*LoginBundle) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *LoginBundle) GetLoginState() LoginState {
	if m != nil {
		return m.LoginState
	}
	return LoginState_Missing
}

func (m *LoginBundle) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *LoginBundle) GetConsumeRedirect() bool {
	if m != nil {
		return m.ConsumeRedirect
	}
	return false
}

func (m *LoginBundle) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

type ApplicationBundle struct {
	// Associate a login state with a single bundle.
	LoginBundle []*LoginBundle `protobuf:"bytes,5,rep,name=LoginBundle" json:"LoginBundle,omitempty"`
	// Configured resource for the authenticator.
	AuthConfiguredResource string `protobuf:"bytes,6,opt,name=AuthConfiguredResource" json:"AuthConfiguredResource,omitempty"`
	// Setup the host names to bind to.
	Host []string `protobuf:"bytes,7,rep,name=Host" json:"Host,omitempty"`
}

func (m *ApplicationBundle) Reset()                    { *m = ApplicationBundle{} }
func (m *ApplicationBundle) String() string            { return proto.CompactTextString(m) }
func (*ApplicationBundle) ProtoMessage()               {}
func (*ApplicationBundle) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *ApplicationBundle) GetLoginBundle() []*LoginBundle {
	if m != nil {
		return m.LoginBundle
	}
	return nil
}

func (m *ApplicationBundle) GetAuthConfiguredResource() string {
	if m != nil {
		return m.AuthConfiguredResource
	}
	return ""
}

func (m *ApplicationBundle) GetHost() []string {
	if m != nil {
		return m.Host
	}
	return nil
}

type ServiceBundle struct {
	// Name is the base name for this service.
	// If something references  "solidcoredata.org/example-1/app" and the base
	// name is "solidcoredata.org/example-1", then the component name that is sent is "app".
	// "solidcoredata.org/example-1" or "solidcoredata.org/library-1".
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	// Resources with potential and configured resources.
	// Also define bundled resources together.
	Resource []*Resource `protobuf:"bytes,2,rep,name=Resource" json:"Resource,omitempty"`
	// Bundle Login bundles together with an auth configured resource and
	// host name list to define an application that can be served.
	Application []*ApplicationBundle `protobuf:"bytes,5,rep,name=Application" json:"Application,omitempty"`
}

func (m *ServiceBundle) Reset()                    { *m = ServiceBundle{} }
func (m *ServiceBundle) String() string            { return proto.CompactTextString(m) }
func (*ServiceBundle) ProtoMessage()               {}
func (*ServiceBundle) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *ServiceBundle) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceBundle) GetResource() []*Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *ServiceBundle) GetApplication() []*ApplicationBundle {
	if m != nil {
		return m.Application
	}
	return nil
}

func init() {
	proto.RegisterType((*NotifyReq)(nil), "api.NotifyReq")
	proto.RegisterType((*UpdateReq)(nil), "api.UpdateReq")
	proto.RegisterType((*UpdateResp)(nil), "api.UpdateResp")
	proto.RegisterType((*ServiceConfigEndpoint)(nil), "api.ServiceConfigEndpoint")
	proto.RegisterType((*ServiceConfig)(nil), "api.ServiceConfig")
	proto.RegisterType((*Resource)(nil), "api.Resource")
	proto.RegisterType((*LoginBundle)(nil), "api.LoginBundle")
	proto.RegisterType((*ApplicationBundle)(nil), "api.ApplicationBundle")
	proto.RegisterType((*ServiceBundle)(nil), "api.ServiceBundle")
	proto.RegisterEnum("api.UpdateAction", UpdateAction_name, UpdateAction_value)
	proto.RegisterEnum("api.ServiceConfigAction", ServiceConfigAction_name, ServiceConfigAction_value)
	proto.RegisterEnum("api.ResourceType", ResourceType_name, ResourceType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Routes service

type RoutesClient interface {
	UpdateServiceBundle(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (Routes_UpdateServiceBundleClient, error)
	// Update connected services information, such as other service locations and SPA code and configs.
	UpdateServiceConfig(ctx context.Context, in *ServiceConfig, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type routesClient struct {
	cc *grpc.ClientConn
}

func NewRoutesClient(cc *grpc.ClientConn) RoutesClient {
	return &routesClient{cc}
}

func (c *routesClient) UpdateServiceBundle(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (Routes_UpdateServiceBundleClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Routes_serviceDesc.Streams[0], c.cc, "/api.Routes/UpdateServiceBundle", opts...)
	if err != nil {
		return nil, err
	}
	x := &routesUpdateServiceBundleClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Routes_UpdateServiceBundleClient interface {
	Recv() (*ServiceBundle, error)
	grpc.ClientStream
}

type routesUpdateServiceBundleClient struct {
	grpc.ClientStream
}

func (x *routesUpdateServiceBundleClient) Recv() (*ServiceBundle, error) {
	m := new(ServiceBundle)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *routesClient) UpdateServiceConfig(ctx context.Context, in *ServiceConfig, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/api.Routes/UpdateServiceConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Routes service

type RoutesServer interface {
	UpdateServiceBundle(*google_protobuf1.Empty, Routes_UpdateServiceBundleServer) error
	// Update connected services information, such as other service locations and SPA code and configs.
	UpdateServiceConfig(context.Context, *ServiceConfig) (*google_protobuf1.Empty, error)
}

func RegisterRoutesServer(s *grpc.Server, srv RoutesServer) {
	s.RegisterService(&_Routes_serviceDesc, srv)
}

func _Routes_UpdateServiceBundle_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(google_protobuf1.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RoutesServer).UpdateServiceBundle(m, &routesUpdateServiceBundleServer{stream})
}

type Routes_UpdateServiceBundleServer interface {
	Send(*ServiceBundle) error
	grpc.ServerStream
}

type routesUpdateServiceBundleServer struct {
	grpc.ServerStream
}

func (x *routesUpdateServiceBundleServer) Send(m *ServiceBundle) error {
	return x.ServerStream.SendMsg(m)
}

func _Routes_UpdateServiceConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoutesServer).UpdateServiceConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Routes/UpdateServiceConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoutesServer).UpdateServiceConfig(ctx, req.(*ServiceConfig))
	}
	return interceptor(ctx, in, info, handler)
}

var _Routes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Routes",
	HandlerType: (*RoutesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateServiceConfig",
			Handler:    _Routes_UpdateServiceConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UpdateServiceBundle",
			Handler:       _Routes_UpdateServiceBundle_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "router.proto",
}

// Client API for RouterConfiguration service

type RouterConfigurationClient interface {
	Notify(ctx context.Context, in *NotifyReq, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	Update(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*UpdateResp, error)
}

type routerConfigurationClient struct {
	cc *grpc.ClientConn
}

func NewRouterConfigurationClient(cc *grpc.ClientConn) RouterConfigurationClient {
	return &routerConfigurationClient{cc}
}

func (c *routerConfigurationClient) Notify(ctx context.Context, in *NotifyReq, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/api.RouterConfiguration/Notify", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerConfigurationClient) Update(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*UpdateResp, error) {
	out := new(UpdateResp)
	err := grpc.Invoke(ctx, "/api.RouterConfiguration/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RouterConfiguration service

type RouterConfigurationServer interface {
	Notify(context.Context, *NotifyReq) (*google_protobuf1.Empty, error)
	Update(context.Context, *UpdateReq) (*UpdateResp, error)
}

func RegisterRouterConfigurationServer(s *grpc.Server, srv RouterConfigurationServer) {
	s.RegisterService(&_RouterConfiguration_serviceDesc, srv)
}

func _RouterConfiguration_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterConfigurationServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.RouterConfiguration/Notify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterConfigurationServer).Notify(ctx, req.(*NotifyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterConfiguration_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterConfigurationServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.RouterConfiguration/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterConfigurationServer).Update(ctx, req.(*UpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _RouterConfiguration_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.RouterConfiguration",
	HandlerType: (*RouterConfigurationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Notify",
			Handler:    _RouterConfiguration_Notify_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _RouterConfiguration_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "router.proto",
}

func init() { proto.RegisterFile("router.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 729 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xdd, 0x6e, 0xda, 0x48,
	0x14, 0x8e, 0x81, 0x98, 0x70, 0xf8, 0x73, 0x06, 0x2d, 0xb2, 0xd8, 0x9b, 0xc8, 0xda, 0x5d, 0x25,
	0xac, 0x44, 0x22, 0x22, 0xad, 0xf6, 0x96, 0xd0, 0x48, 0x8d, 0x14, 0x91, 0x74, 0x68, 0x7a, 0xef,
	0xe0, 0x03, 0xb1, 0x0a, 0x1e, 0x77, 0x3c, 0x8e, 0xca, 0x1b, 0x54, 0xea, 0x4d, 0xa5, 0xde, 0xf6,
	0x89, 0xfa, 0x54, 0xd5, 0x8c, 0x67, 0x0c, 0x26, 0xa1, 0x77, 0x73, 0xbe, 0x73, 0xe6, 0xcc, 0xf7,
	0xcd, 0xf9, 0x81, 0x06, 0x67, 0xa9, 0x40, 0x3e, 0x88, 0x39, 0x13, 0x8c, 0x94, 0xfd, 0x38, 0xec,
	0xfd, 0xb9, 0x60, 0x6c, 0xb1, 0xc4, 0x73, 0x05, 0x3d, 0xa6, 0xf3, 0x73, 0x5c, 0xc5, 0x62, 0x9d,
	0x45, 0xf4, 0xc0, 0x4f, 0xc5, 0x53, 0x76, 0xf6, 0x2e, 0xa1, 0x36, 0x61, 0x22, 0x9c, 0xaf, 0x29,
	0x7e, 0x22, 0xff, 0x40, 0x6b, 0x8a, 0xfc, 0x39, 0x9c, 0xe1, 0x28, 0x08, 0x38, 0x26, 0x89, 0x6b,
	0x9d, 0x58, 0xa7, 0x35, 0xba, 0x83, 0x7a, 0xcf, 0x50, 0x7b, 0x88, 0x03, 0x5f, 0xa0, 0xbc, 0x74,
	0x06, 0xf6, 0x68, 0x26, 0x42, 0x16, 0xa9, 0xe0, 0xd6, 0xf0, 0x78, 0xe0, 0xc7, 0xe1, 0x20, 0xf3,
	0x67, 0x0e, 0xaa, 0x03, 0x08, 0x81, 0xca, 0x55, 0x18, 0x05, 0x6e, 0x49, 0x65, 0x55, 0x67, 0x89,
	0xbd, 0x65, 0x89, 0x70, 0xcb, 0x27, 0x65, 0x89, 0xc9, 0x33, 0xe9, 0x82, 0x7d, 0x95, 0x46, 0xc1,
	0x12, 0xdd, 0x8a, 0x42, 0xb5, 0xe5, 0x35, 0x00, 0xcc, 0xbb, 0x49, 0xec, 0x71, 0xf8, 0x43, 0xf3,
	0x1a, 0xb3, 0x68, 0x1e, 0x2e, 0xae, 0xa3, 0x20, 0x66, 0x61, 0x24, 0x64, 0xca, 0x89, 0xbf, 0x42,
	0x4d, 0x5e, 0x9d, 0x49, 0x0f, 0x8e, 0x8c, 0x5f, 0x3f, 0x9f, 0xdb, 0xe4, 0x0c, 0x8e, 0x28, 0x26,
	0x2c, 0xe5, 0x33, 0x54, 0x34, 0xea, 0xc3, 0xa6, 0xd2, 0x60, 0x40, 0x9a, 0xbb, 0xbd, 0xaf, 0x16,
	0x34, 0x0b, 0x8f, 0x12, 0x17, 0xaa, 0x1f, 0x90, 0x27, 0x46, 0x7f, 0x8d, 0x1a, 0x93, 0x5c, 0xe4,
	0x1f, 0x53, 0x52, 0x1f, 0xe3, 0xaa, 0xa4, 0x85, 0xdb, 0x3b, 0xff, 0x33, 0x80, 0xca, 0x6d, 0xa8,
	0xff, 0xa2, 0x3e, 0xec, 0xbd, 0x8c, 0x37, 0x94, 0xa9, 0x8a, 0xf3, 0x7e, 0x5a, 0x1b, 0xe6, 0xaf,
	0xaa, 0xee, 0x82, 0x7d, 0xef, 0x73, 0xcc, 0x35, 0x6b, 0x8b, 0xfc, 0x0d, 0x95, 0xf7, 0xeb, 0x58,
	0xaa, 0xdd, 0x54, 0xcc, 0x24, 0x92, 0x0e, 0xaa, 0xdc, 0xe4, 0x5f, 0xa8, 0x8e, 0x59, 0x94, 0xa4,
	0x2b, 0x59, 0x88, 0x3d, 0x91, 0x26, 0x82, 0xfc, 0x05, 0xcd, 0x8c, 0x64, 0xca, 0x7d, 0xa5, 0xfa,
	0xf0, 0xc4, 0x3a, 0x6d, 0xd0, 0x22, 0x28, 0xbf, 0xeb, 0x26, 0x9a, 0x2d, 0xd3, 0x00, 0x5d, 0x5b,
	0xd5, 0xd6, 0x98, 0xde, 0x0f, 0x0b, 0xea, 0xb7, 0x6c, 0x11, 0x46, 0x59, 0xb1, 0xc9, 0x39, 0x80,
	0x32, 0xa7, 0xc2, 0x17, 0xa8, 0x7b, 0xab, 0xad, 0xde, 0xdf, 0xc0, 0x74, 0x2b, 0x44, 0x89, 0xe5,
	0x38, 0x0f, 0x3f, 0xe7, 0x62, 0x95, 0x45, 0x4e, 0xa1, 0xad, 0x39, 0x52, 0x0c, 0x42, 0x8e, 0x33,
	0xa1, 0x74, 0x1f, 0xd1, 0x5d, 0x58, 0x36, 0x49, 0xde, 0x08, 0x95, 0xac, 0x49, 0xf2, 0xca, 0x7f,
	0xb7, 0xe0, 0x78, 0x14, 0xc7, 0xcb, 0x70, 0xa6, 0x84, 0x68, 0x92, 0xc3, 0x02, 0x67, 0xf7, 0x50,
	0x15, 0xce, 0xd9, 0xb0, 0xcc, 0x70, 0x5a, 0x10, 0xf6, 0x1f, 0x74, 0x47, 0xa9, 0x78, 0x32, 0xff,
	0x82, 0x41, 0xfe, 0xa6, 0xad, 0xde, 0xdc, 0xe3, 0xcd, 0x27, 0xa5, 0xba, 0x99, 0x14, 0xef, 0xcb,
	0xa6, 0x1f, 0x75, 0xf6, 0xd7, 0xda, 0x60, 0xbb, 0xc1, 0x4b, 0xbf, 0x6d, 0x70, 0xf2, 0x3f, 0xd4,
	0xb7, 0x54, 0x6a, 0x41, 0x5d, 0x15, 0xfd, 0x42, 0x3d, 0xdd, 0x0e, 0xed, 0x4f, 0xa1, 0xb1, 0x3d,
	0xf4, 0xa4, 0x65, 0x86, 0x75, 0x72, 0x77, 0x77, 0xef, 0x1c, 0x10, 0xc7, 0xf8, 0x6f, 0xa2, 0x04,
	0xb9, 0x70, 0x2c, 0xd2, 0x86, 0xba, 0xbe, 0xb1, 0x14, 0xc8, 0x9d, 0xd2, 0x26, 0xe4, 0x0d, 0x2e,
	0x51, 0xa0, 0x53, 0xee, 0xf7, 0xa1, 0xf3, 0xca, 0xc0, 0x90, 0x2a, 0x94, 0x47, 0x41, 0xe0, 0x1c,
	0x10, 0x00, 0x9b, 0xe2, 0x8a, 0x3d, 0xa3, 0x63, 0xf5, 0x3f, 0x42, 0x63, 0xbb, 0x33, 0x65, 0x36,
	0x63, 0x4f, 0x58, 0x84, 0xce, 0x81, 0x7c, 0xd0, 0x20, 0x0f, 0xf4, 0xd6, 0xb1, 0x48, 0x07, 0xda,
	0x06, 0x98, 0xde, 0x8f, 0xc6, 0x2c, 0xc0, 0x8c, 0x85, 0x01, 0x65, 0x25, 0x9c, 0x0a, 0x39, 0x86,
	0xa6, 0x41, 0xde, 0xa5, 0xc8, 0xd7, 0xce, 0xe1, 0xf0, 0x9b, 0x05, 0x36, 0x95, 0x6b, 0x37, 0x21,
	0x63, 0xe8, 0x64, 0xac, 0x8b, 0x85, 0xe8, 0x0e, 0xb2, 0x1d, 0x3c, 0x30, 0x3b, 0x78, 0x70, 0x2d,
	0x77, 0x70, 0x8f, 0x6c, 0x8f, 0x75, 0x16, 0x7b, 0x61, 0x91, 0xd1, 0x4e, 0x12, 0xbd, 0x5d, 0xc8,
	0xcb, 0x1d, 0xd0, 0xdb, 0x93, 0x78, 0xc8, 0xa1, 0xa3, 0x18, 0xf1, 0xe2, 0xc4, 0x5d, 0x80, 0x9d,
	0x6d, 0x78, 0xd2, 0x52, 0xc9, 0xf2, 0x75, 0xbf, 0x2f, 0x91, 0xdc, 0xe8, 0x19, 0x17, 0x7d, 0x23,
	0xdf, 0xf5, 0xbd, 0x76, 0xc1, 0x4e, 0xe2, 0x47, 0x5b, 0x5d, 0xbd, 0xfc, 0x15, 0x00, 0x00, 0xff,
	0xff, 0xf5, 0x36, 0x13, 0xc7, 0x83, 0x06, 0x00, 0x00,
}
