// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spa.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type FetchUIRequest struct {
	List []string `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
}

func (m *FetchUIRequest) Reset()                    { *m = FetchUIRequest{} }
func (m *FetchUIRequest) String() string            { return proto.CompactTextString(m) }
func (*FetchUIRequest) ProtoMessage()               {}
func (*FetchUIRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *FetchUIRequest) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

type FetchUIResponse struct {
	List []*FetchUIItem `protobuf:"bytes,1,rep,name=List" json:"List,omitempty"`
}

func (m *FetchUIResponse) Reset()                    { *m = FetchUIResponse{} }
func (m *FetchUIResponse) String() string            { return proto.CompactTextString(m) }
func (*FetchUIResponse) ProtoMessage()               {}
func (*FetchUIResponse) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *FetchUIResponse) GetList() []*FetchUIItem {
	if m != nil {
		return m.List
	}
	return nil
}

type FetchUIItem struct {
	Name string `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Body string `protobuf:"bytes,2,opt,name=Body" json:"Body,omitempty"`
}

func (m *FetchUIItem) Reset()                    { *m = FetchUIItem{} }
func (m *FetchUIItem) String() string            { return proto.CompactTextString(m) }
func (*FetchUIItem) ProtoMessage()               {}
func (*FetchUIItem) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *FetchUIItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FetchUIItem) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*FetchUIRequest)(nil), "api.FetchUIRequest")
	proto.RegisterType((*FetchUIResponse)(nil), "api.FetchUIResponse")
	proto.RegisterType((*FetchUIItem)(nil), "api.FetchUIItem")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SPA service

type SPAClient interface {
	// TODO: RequestAuth and Login should both take some additional features
	// about where the request is coming from (HTTPS info, remote address).
	FetchUI(ctx context.Context, in *FetchUIRequest, opts ...grpc.CallOption) (*FetchUIResponse, error)
}

type sPAClient struct {
	cc *grpc.ClientConn
}

func NewSPAClient(cc *grpc.ClientConn) SPAClient {
	return &sPAClient{cc}
}

func (c *sPAClient) FetchUI(ctx context.Context, in *FetchUIRequest, opts ...grpc.CallOption) (*FetchUIResponse, error) {
	out := new(FetchUIResponse)
	err := grpc.Invoke(ctx, "/api.SPA/FetchUI", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SPA service

type SPAServer interface {
	// TODO: RequestAuth and Login should both take some additional features
	// about where the request is coming from (HTTPS info, remote address).
	FetchUI(context.Context, *FetchUIRequest) (*FetchUIResponse, error)
}

func RegisterSPAServer(s *grpc.Server, srv SPAServer) {
	s.RegisterService(&_SPA_serviceDesc, srv)
}

func _SPA_FetchUI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchUIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SPAServer).FetchUI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SPA/FetchUI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SPAServer).FetchUI(ctx, req.(*FetchUIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SPA_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.SPA",
	HandlerType: (*SPAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchUI",
			Handler:    _SPA_FetchUI_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spa.proto",
}

func init() { proto.RegisterFile("spa.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x2e, 0x48, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0x52, 0xe1, 0xe2, 0x73, 0x4b,
	0x2d, 0x49, 0xce, 0x08, 0xf5, 0x0c, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62,
	0xf1, 0xc9, 0x2c, 0x2e, 0x91, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0xcc, 0xb9,
	0xf8, 0xe1, 0xaa, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x54, 0x90, 0x94, 0x71, 0x1b, 0x09,
	0xe8, 0x25, 0x16, 0x64, 0xea, 0x41, 0xd5, 0x78, 0x96, 0xa4, 0xe6, 0x42, 0x35, 0x9a, 0x72, 0x71,
	0x23, 0x09, 0x82, 0xcc, 0xf6, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0x04, 0x99, 0x0d, 0x62,
	0x83, 0xc4, 0x9c, 0xf2, 0x53, 0x2a, 0x25, 0x98, 0x20, 0x62, 0x20, 0xb6, 0x91, 0x35, 0x17, 0x73,
	0x70, 0x80, 0xa3, 0x90, 0x09, 0x17, 0x3b, 0x54, 0xb7, 0x90, 0x30, 0xb2, 0x05, 0x50, 0xa7, 0x4a,
	0x89, 0xa0, 0x0a, 0x42, 0x5c, 0x96, 0xc4, 0x06, 0xf6, 0x9e, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0xd0, 0x50, 0xb3, 0x36, 0xeb, 0x00, 0x00, 0x00,
}
